name: "Publish LDLT Editions"
on: 
  push:
    paths:
      - sources/*.xml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: files
        uses: jitterbit/get-changed-files@v1
      - run: echo "FILES=\"${{ steps.files.outputs.added_modified }}\"" >> $GITHUB_ENV 
      - uses: ./.github/actions/publish
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Published ${{ steps.files.outputs.added_modified }}